services:
  stats-server:
    build:
      context: ./stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statspassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=always
      - SERVER_PORT=9090

  stats-db:
    image: postgres:16.1
    container_name: explore_with_me_stats_database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=statspassword
    volumes:
      - stats_data_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U statsuser -d statsdb -h stats-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build:
      context: ./main-service
    image: java-explore-with-me-main-service:latest
    container_name: explore_with_me_main_service
    depends_on:
      ewm-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewmdb
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=ewmpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=always
      - SERVER_PORT=8080
      - STATS_SERVER_URL=http://stats-server:9090
      - APP_NAME=main-service
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 5

  ewm-db:
    image: postgres:16.1
    container_name: explore_with_me_main_database
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewmdb
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmpassword
    volumes:
      - ewm_data_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewmuser -d ewmdb -h ewm-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  stats_data_volume:
  ewm_data_volume:
