services:
  stats-server:
    image: stats-server
    build: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statspassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_SQL_INIT_MODE=always
    restart: unless-stopped

  stats-db:
    image: postgres:16.1
    container_name: explore_with_me_stats_database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=statspassword
    volumes:
      - stats_data_volume:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U statsuser -d statsdb -h stats-db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    image: alpine:latest
    container_name: explore_with_me_main_service_placeholder
    restart: "no"

volumes:
  stats_data_volume: